import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import LightRays from "@/components/ui/LightRays/LightRays";

export const metadata = {
  title: "null | VIT Bhopal",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon.ico",
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased bg-neutral-900 text-gray-100 `}>
        <div style={{ width: "100%", height: "100vh", position: "fixed" }}>
          <LightRays
            raysOrigin="top-center"
            raysColor="#b3b3b3"
            raysSpeed={1}
            lightSpread={0.8}
            rayLength={3}
            fadeDistance={2}
            followMouse={true}
            mouseInfluence={0.1}
            noiseAmount={0.1}
            distortion={0.05}
            saturation={1}
            className=""
          />
        </div>
        <Navbar />
        <main className="max-h-[90vh] max-w-screen relative sm:top-[90px] top-20">
          {children}
        </main>
      </body>
    </html>
  );
}
