import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import Background from "@/components/Background";
import Footer from "@/components/Footer";

export const metadata = {
  title: "null | VIT Bhopal",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon.ico",
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased bg-neutral-900 text-gray-100 `}>
        <Background />
        <Navbar />
        <main className=" max-w-screen relative sm:top-[90px] top-20 min-h-screen">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
